# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee81e7b8232b5c5c12cf05663326aa16a58bd4c6189b2da1a3cc00d7bf9e51f26752d2a9b6bde1d9ec91ba6a11423bb2ab25d5a0c191d6799f0d07e3889ea4a

test:
  secret_key_base: dec9dba92b652a5cb601da33b60cab9bbf017b616b173ea1d91f2621c100579a998ab063a15c6cd71b28d10025988d472afbd6e9e77cbf9964ca4a9f75b59a6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
